//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Пиши_Стирай.Entities
{
    using System;
    using System.Collections.Generic;
    using Пиши_Стирай.Classes;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderProducts = new HashSet<OrderProduct>();
        }
    
        public string ProductArticleNumber { get; set; }
        public Nullable<int> ProductCategoryId { get; set; }
        public Nullable<int> ProductManufacturerId { get; set; }
        public Nullable<int> ProductSupplierId { get; set; }
        public string ProductName { get; set; }
        public string ProductUnit { get; set; }
        public string ProductDescription { get; set; }
        public string ProductPhoto { get; set; }
        public decimal ProductCost { get; set; }
        public Nullable<int> ProductMaxDiscount { get; set; }
        public Nullable<int> ProductDiscountAmount { get; set; }
        public int ProductQuantityInStock { get; set; }
        public string ProductStatus { get; set; }
    
        public virtual Category Category { get; set; }

        /// <summary>
        /// Производитель.
        /// </summary>
        public virtual Company Company { get; set; }

        /// <summary>
        /// Поставщик.
        /// </summary>
        public virtual Company Company1 { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderProduct> OrderProducts { get; set; }

        public String SafeProductPhoto
        {
            get
            {
                return ResourceManager.GetSafeImage(ProductPhoto);
            }
        }

        public String ProductManufacturer_Bind
        {
            get
            {
                return $"Производитель: {Company.CompanyName}.";
            }
        }

        public Decimal AbsoluteDiscount
        {
            get
            {
                return ProductCost * Convert.ToDecimal((Convert.ToDouble(ProductDiscountAmount) / 100.0));
            }
        }

        public Decimal FinalCost
        {
            get
            {
                return ProductCost - AbsoluteDiscount;
            }
        }
    }
}
